import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import {getServerSession} from "next-auth";
import SessionProvider from "@/components/SessionProvider";
import Providers from "@/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await getServerSession()
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
      <SessionProvider session={session}>
          <Providers>{children}</Providers>
      </SessionProvider>

      </body>
    </html>
  );
}
