import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Providers from "@/Providers";
import styles from "@/application.module.scss";
import React from "react";

export const metadata: Metadata = {
  title: "C11",
  description: "Generated by create next app",
};
const poppins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
          <Providers>
              <div className={styles['application-wrapper']}>
                  {modal}
                  {children}
              </div>
          </Providers>
      </body>
    </html>
  );
}
